### ISSUE TITLE
Where are we to place "credentialStatus".

### ISSUE THREAD

**Issue by azuzi** [uport-project/credential-status#22]
Hi,
The W3C [Verifiable Credential Data Model](https://www.w3.org/TR/vc-data-model/#example-28-jwt-payload-of-a-jwt-based-verifiable-credential-using-jws-as-a-proof-non-normative) the status field is placed within 'VC'. 
But here "crdentialStatus" is placed within the JWT payload and also the verification of the VC also looking into the payload, not within the 'VC'. 
Can anyone please explain how this works?

**Comment by mirceanis** [comment]
Hi,
The link you posted points to the `credentialSubject`, not the `credentialStatus`
There is a bit of confusion when it comes to translating between the JSON and JWT payload encodings for properties of a credential.
The VC data model only gives an example for the JSON case, so the JWT encoding is only adapted.

In this library, the credentialStatus field is expected as a top level property of the credential payload; however, this is not set in stone so it can be changed if the standards change.
